### ISSUE TITLE
Godiva3.html not working

### ISSUE THREAD

**Issue by UAEpro** [Reading-eScience-Centre/ncwms#19]
Hello,
I have an issue with Godiva3 with the latest version
i got this error from the console
```
Error initializing web application: prefix []
java.lang.IncompatibleClassChangeError: Expected static field uk.ac.rdg.resc.edal.ncwms.NcwmsCatalogue.cacheManager
	at uk.ac.rdg.resc.edal.ncwms.NcwmsCatalogue.<init>(NcwmsCatalogue.java:85)
	at uk.ac.rdg.resc.edal.ncwms.NcwmsApplicationServlet.init(NcwmsApplicationServlet.java:297)
	at winstone.ServletConfiguration.ensureInitialization(ServletConfiguration.java:183)
	at winstone.WebAppConfiguration.<init>(WebAppConfiguration.java:918)
	at winstone.HostConfiguration.initWebApp(HostConfiguration.java:131)
	at winstone.HostConfiguration.<init>(HostConfiguration.java:73)
	at winstone.HostGroup.initHost(HostGroup.java:85)
	at winstone.HostGroup.<init>(HostGroup.java:45)
	at winstone.Launcher.<init>(Launcher.java:196)
	at winstone.Launcher.main(Launcher.java:391)
```
and this is the error from the web console 

```
SEVERE: (TypeError) : Cannot read property 'length' of undefinedcom.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'length' of undefined
	at Unknown.hgb(godiva3-0.js)
	at Unknown.wgb(godiva3-0.js)
	at Unknown.Kcb(godiva3-0.js)
	at Unknown.Lcb(godiva3-0.js)
	at Unknown.cdb(godiva3-0.js)
	at Unknown.vo(godiva3-0.js)
	at Unknown.Ho(godiva3-0.js)
	at Unknown.eval(godiva3-0.js)
	at Unknown.xg(godiva3-0.js)
	at Unknown.Ag(godiva3-0.js)
	at Unknown.eval(godiva3-0.js)

YH @ godiva3-0.js:2122
pI @ godiva3-0.js:1962
oI @ godiva3-0.js:1479
a9 @ godiva3-0.js:422
Fg @ godiva3-0.js:1656
Ag @ godiva3-0.js:1853
(anonymous) @ godiva3-0.js:1746
```

**Comment by guygriffiths** [comment]
Can you provide any more information on the error?  It looks like you are running the standalone version of ncWMS2, can you confirm that it's the latest 2.2.12 version downloaded from [here](https://github.com/Reading-eScience-Centre/ncwms/releases/tag/ncwms-2.2.12)?  I haven't been able to reproduce the error, so any additional information you can supply would be useful.
