### ISSUE TITLE
Using crs_wkt

### ISSUE THREAD

**Issue by ludvikbrodl** [Reading-eScience-Centre/ncwms#38]
I'm trying to use crs_wkt to define a dataset's projection, however can not get it working. Does ncWMS2 implement cf conventions 1.7? The documentation says "The CF conventions are the primary standard used in ncWMS." But not up until which conventionversion and not to what extend it implements the convention.

More specifically where is the projection decided in ncWMS2 and in what order. I should be able to answer this question myself if I found the specific source code but have thus far been unable.

**Comment by guygriffiths** [comment]
Unfortunately, ncWMS2 only supports v1.6 of the CF conventions and currently requires that a 2D lat/lon grid is used to define the coordinates.  If you send me a sample file I can look into implementing it though.

**Comment by ludvikbrodl** [comment]
That is great news! I'm attaching a dataset that works fine in ncWMS2 and then one which does not work, with a crs_wkt but no lon lat, that I would benefit greatly were it functional.

[crs_wkt.zip](https://github.com/Reading-eScience-Centre/ncwms/files/2643869/crs_wkt.zip)
ignore the EPSG_28992:spatial_ref, it exists for another application.

**Comment by guygriffiths** [comment]
I've had a look into this, but I think the issue is with the Unidata libraries we use to read NetCDF.

@lesserwhirls - Any ideas on this?  I'm opening the NetcdfDataset as a `ucar.nc2.dt.grid.GridDataset`, but it's not finding any grids (i.e. `gridDataset.getGrids().size() == 0`) with version 5.0.0-beta6.  Is there a way I can open this as a gridded dataset so that I can pull out the `Projection` object and use that for co-ordinate transforms?

**Comment by lesserwhirls** [comment]
I'm not certain about wkt support in netCDF-Java. We do have a wkt parser, but it is failing on trying to parse the string contained in the sample file:

~~~java
Exception in thread "main" java.text.ParseException: expected ]
	at ucar.unidata.geoloc.ogc.WKTParser.eatCloseBrace(WKTParser.java:284)
	at ucar.unidata.geoloc.ogc.WKTParser.eatSpheroid(WKTParser.java:426)
	at ucar.unidata.geoloc.ogc.WKTParser.eatDatum(WKTParser.java:395)
	at ucar.unidata.geoloc.ogc.WKTParser.parseGeogcs(WKTParser.java:375)
	at ucar.unidata.geoloc.ogc.WKTParser.parseProjcs(WKTParser.java:297)
	at ucar.unidata.geoloc.ogc.WKTParser.<init>(WKTParser.java:126)
	at ucar.unidata.geoloc.ogc.WKTParser.main(WKTParser.java:721)
~~~

**Comment by ludvikbrodl** [comment]
I tried to replicate your crash @lesserwhirls but I'm unsure what version or how you opened the netCDF file I provided. netCDF-Java does not seem to crash when inputing the string manually into the code.

Try
```
javac -cp '.:netcdfAll-4.6.jar' read_crs_wkt.java && java -cp '.:netcdfAll-4.6.jar' read_crs_wkt
```
from 

[read_crs_wkt.java.zip](https://github.com/Reading-eScience-Centre/ncwms/files/2676260/read_crs_wkt.java.zip)
along with ftp://ftp.unidata.ucar.edu/pub/netcdf-java/v4.6/netcdfAll-4.6.jar
(Excuse my java, haven't written any in many years)

**Comment by lesserwhirls** [comment]
Hi @ludvikbrodl - what I did was added some code in the `main` method of the `WKTParser` to open the file and read the `crs_wkt` attribute, like so:

~~~java
  public static void main(String[] args) throws IOException, ParseException {
    String testFile = "C:/Users/lesserwhirls/Downloads/res_16_no_lonlat.nc";
    NetcdfFile ncf = NetcdfFile.open(testFile);
    Variable var = ncf.findVariable("EPSG_28992");
    Attribute attr = ((Variable) var).findAttribute("crs_wkt");
    String wkt = attr.getStringValue();
    WKTParser p = new WKTParser(wkt);
    ProjectionImpl proj = convertWKTToProjection(p);
}
~~~
I also get the error if I use the `spatial_ref` attribute instead of the `crs_wkt` attribute.

I did this using version 5 of the code base (which is what `edal-java` is using), but I'd expect something similar in 4.6 as the `WKTParser` class hasn't changed.

I checked the wkt string in your code, and it works in version 5, but that's different than the one in the netCDF file.

**Comment by ludvikbrodl** [comment]
You are correct, I was using a different WKT than the one I provided when testing netCDF-java, my bad. I get your crash when I use the netCDF file I provided in the previous post. I have found the culprits in the WKT provided which  `ucar.unidata.geoloc.ogc.WKTParser` cannot handle.

It is the "AUTHORITY" parameter in GEOGC, DATUM, SPHEROID, PRIMEM, UNIT, and PROJCS. I modified the crs_wkt in the attached netCDF `res_16_no_lonlat_trimmed_wkt.nc` file to not include these, if it will help you move forward. (However, netCDF-Java should probably be able to handle them in the future aswell). I've also included a java file which produces the crash if you want to debug some more on that end.

[read_crs_wkt_v2.zip.zip](https://github.com/Reading-eScience-Centre/ncwms/files/2680094/read_crs_wkt_v2.zip.zip)

I am unsure what the AUTHORITY parameter provides more than metadata, it should not affect the projection and works fine without it in QGIS/GDAL.

The reason for me wanting to use the crs_wkt is that I use gdal alot, with many different projections. This becomes a hassle when every time I need to create some netCDF file I have to go through http://cfconventions.org/wkt-proj-4.html to produce my own netCDF grid_mapping. This is tedious, unrewarding, and very prone to error.

**Comment by lesserwhirls** [comment]
I can certainly understand that producing standards compliant files can be a not-so-fun process. I can try to modify the CF coordinate builder class to use the information in the `crs_wkt` attribute of the `grid_mapping` variable as a last resort when building the coordinate system (likely starting somewhere around [here](https://github.com/Unidata/thredds/blob/351c703c5ac6def728704716be430412a9ce4c87/cdm/src/main/java/ucar/nc2/dataset/conv/CF1Convention.java#L150)). However, you'll need to make sure you set the global attribute `Conventions = CF-1.7` in your file to make sure that builder gets used. @ethanrd - any opinion on this approach?

I should also note that to be fully CF compliant, you would [still need to include the single-property CF grid mapping attributes](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#use-of-the-crs-well-known-text-format):

> The crs_wkt attribute is intended to act as a _supplement_ to other single-property CF grid mapping attributes (as described in Appendix F); it is not intended to replace those attributes.
