### ISSUE TITLE
Unable to load CF-1.0

### ISSUE THREAD

**Issue by ZihengSun** [Reading-eScience-Centre/ncwms#45]
Hi All, meet problem while loading CF-1.0 netcdf files. The system throws a exception:
```
uk.ac.rdg.resc.edal.exceptions.DataReadingException: No grids found in underlying NetCDF dataset
	at uk.ac.rdg.resc.edal.util.cdm.CdmUtils.getGridDataset(CdmUtils.java:123)
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.getNonStaggeredGriddedVariableMetadata(CdmGridDatasetFactory.java:143)
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.generateGridDataset(CdmGridDatasetFactory.java:134)
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmGridDatasetFactory.generateDataset(CdmGridDatasetFactory.java:124)
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:88)
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:72)
```
Can anyone tell me what is wrong with this file?
```
netcdf file:/D:/work/TESTDATA/earthcube/omega.200606.nc {
  dimensions:
    y = 277;
    x = 349;
    level = 29;
    time = UNLIMITED;   // (240 currently)
  variables:
    float lat(y=277, x=349);
      :long_name = "latitude";
      :units = "degrees_north";
      :standard_name = "latitude";
      :axis = "Y";
      :coordinate_defines = "point";

    float lon(y=277, x=349);
      :units = "degrees_east";
      :long_name = "longitude";
      :standard_name = "longitude";
      :axis = "X";
      :coordinate_defines = "point";

    float xdist(x=349);
      :long_name = "eastward distance from southwest corner of domain in projection coordinates";
      :units = "m";

    float ydist(y=277);
      :long_name = "northward distance from southwest corner of domain in projection coordinates";
      :units = "m";

    float omega(time=240, level=29, y=277, x=349);
      :long_name = "3-hourly Omega on Pressure Levels";
      :unpacked_valid_range = -11.0f, 8.0f; // float
      :actual_range = -10.700377f, 6.0014563f; // float
      :units = "Pascal/s";
      :precision = 3S; // short
      :least_significant_digit = 3S; // short
      :GRIB_id = 135S; // short
      :GRIB_name = "VVEL";
      :var_desc = "Omega (dp/dt)";
      :dataset = "NARR 3-hourly";
      :level_desc = "Pressure Levels";
      :statistic = "Individual Obs";
      :parent_stat = "Other";
      :standard_name = "omega";

    float level(level=29);
      :units = "millibar";
      :actual_range = 1000.0f, 100.0f; // float
      :long_name = "Level";
      :positive = "down";
      :GRIB_id = 100S; // short
      :GRIB_name = "hPa";
      :axis = "Z";
      :coordinate_defines = "point";
      :_CoordinateAxisType = "Pressure";
      :_CoordinateZisPositive = "down";

    double time(time=240);
      :units = "hours since 1800-1-1 00:00:0.0";
      :long_name = "Time";
      :actual_range = 1809384.0, 1810101.0; // double
      :delta_t = "0000-00-00 03:00:00";
      :standard_name = "time";
      :axis = "T";
      :coordinate_defines = "point";
      :calendar = "gregorian";
      :_CoordinateAxisType = "Time";

  // global attributes:
  :Conventions = "CF-1.0";
  :title = "8x Daily NARR";
  :history = "created 2005/07 by Hoop (netCDF2.3)";
  :comments = "Data is from North American Regional Reanalysis\n(8x/day).  It consists of most variables interpolated to\npressure surfaces from model (sigma) surfaces.";
  :institution = "National Centers for Environmental Prediction";
  :platform = "Model";
  :references = "http://wwwt.emc.ncep.noaa.gov/mmb/rreanl/index.html\nhttp://www.cdc.noaa.gov/cdc/data.narr.html";
  :_CoordSysBuilder = "ucar.nc2.dataset.conv.CF1Convention";
}

```

**Comment by guygriffiths** [comment]
Your data variable, `omega`, needs to declare the 2D coordinates it is using, with an attribute such as `coordinates = "lon lat"`.  See here: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_two_dimensional_latitude_longitude_coordinate_variables

You may also need to make sure that you have x/y coordinate variables (i.e. rename `xdist` and `ydist` to `x` and `y`), but I'm not sure.
