### ISSUE TITLE
Can ncWMS support customized projections other than the native ones?

### ISSUE THREAD

**Issue by LipingDi** [Reading-eScience-Centre/ncwms#47]
Hello, we have successfully deployed ncWMS2 and published CF netcdfs in it. We are wondering if the WMS supports other projections except those native supported ones:
```
<CRS>EPSG:4326</CRS>
<CRS>CRS:84</CRS>
<CRS>EPSG:41001</CRS>
<CRS>EPSG:27700</CRS>
<CRS>EPSG:3408</CRS>
<CRS>EPSG:3409</CRS>
<CRS>EPSG:3857</CRS>
<CRS>EPSG:5041</CRS>
<CRS>EPSG:5042</CRS>
<CRS>EPSG:32661</CRS>
<CRS>EPSG:32761</CRS>
```
What should I do if I want to use EPSG5070?

**Comment by guygriffiths** [comment]
Yes, it does support other projections, but it only advertises the most common ones (otherwise it would be a very long list).
I don't know off the top of my head whether it supports EPSG:5070, I'd recommend trying it.

**Comment by corviday** [comment]
Hello, I have a similar issue. I would like to generate map images in the EPSG:3005 projection, which does not seem to be supported. When I request maps with EPSG:3005 as the CRS parameter, ncWMS logs the following error:

```
2019-10-31 20:18:11 ERROR GISUtils:405 - Problem getting CRS
org.opengis.util.NoSuchIdentifierException: No operation method found for name or identifier “Albers Equal Area”.
	at org.apache.sis.referencing.operation.transform.DefaultMathTransformFactory.getOperationMethod(DefaultMathTransformFactory.java:396)
	at org.apache.sis.referencing.operation.transform.DefaultMathTransformFactory.createParameterizedTransform(DefaultMathTransformFactory.java:1008)
	at org.apache.sis.referencing.operation.DefaultConversion.<init>(DefaultConversion.java:264)
	at org.apache.sis.referencing.operation.DefaultProjection.<init>(DefaultProjection.java:98)
	at org.apache.sis.referencing.operation.SubTypes.create(SubTypes.java:177)
	at org.apache.sis.referencing.operation.DefaultConversion.specialize(DefaultConversion.java:430)
	at org.apache.sis.referencing.crs.AbstractDerivedCRS.createConversionFromBase(AbstractDerivedCRS.java:168)
	at org.apache.sis.referencing.crs.AbstractDerivedCRS.<init>(AbstractDerivedCRS.java:112)
	at org.apache.sis.referencing.crs.DefaultProjectedCRS.<init>(DefaultProjectedCRS.java:157)
	at org.apache.sis.referencing.factory.GeodeticObjectFactory.createProjectedCRS(GeodeticObjectFactory.java:763)
	at org.apache.sis.referencing.factory.sql.EPSGDataAccess.createCoordinateReferenceSystem(EPSGDataAccess.java:1466)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.create(AuthorityFactoryProxy.java:391)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.create(AuthorityFactoryProxy.java:389)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.create(ConcurrentAuthorityFactory.java:1659)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.createCoordinateReferenceSystem(ConcurrentAuthorityFactory.java:857)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.createFromAPI(AuthorityFactoryProxy.java:394)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.createFromAPI(AuthorityFactoryProxy.java:389)
	at org.apache.sis.referencing.factory.MultiAuthoritiesFactory.create(MultiAuthoritiesFactory.java:805)
	at org.apache.sis.referencing.factory.MultiAuthoritiesFactory.createCoordinateReferenceSystem(MultiAuthoritiesFactory.java:866)
	at org.apache.sis.referencing.CRS.forCode(CRS.java:183)
	at uk.ac.rdg.resc.edal.util.GISUtils.getCrs(GISUtils.java:401)
	at uk.ac.rdg.resc.edal.util.GISUtils.parseBbox(GISUtils.java:453)
	at uk.ac.rdg.resc.edal.wms.GetMapParameters.parsePlottingParams(GetMapParameters.java:278)
	at uk.ac.rdg.resc.edal.wms.GetMapParameters.<init>(GetMapParameters.java:127)
	at uk.ac.rdg.resc.edal.wms.WmsServlet.getMap(WmsServlet.java:399)
	at uk.ac.rdg.resc.edal.wms.WmsServlet.dispatchWmsRequest(WmsServlet.java:354)
	at uk.ac.rdg.resc.edal.ncwms.NcwmsServlet.dispatchWmsRequest(NcwmsServlet.java:204)
	at uk.ac.rdg.resc.edal.wms.WmsServlet.doGet(WmsServlet.java:289)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:495)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:767)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1347)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
2019-10-31 20:18:11 WARN  WmsServlet:2675 - Wms Exception caught: "The CRS EPSG:3005 is not supported by this server" from:uk.ac.rdg.resc.edal.util.GISUtils:406
```

Is there a way I can generate EPSG:3005 maps with ncWMS?

Thank you for your help.

**Comment by guygriffiths** [comment]
@corviday - No, unfortunately not, that's the standard message for an unsupported CRS code.  We use a third-party library for CRS support, so it's not something we can easily change.

**Comment by corviday** [comment]
Thank you for your help.

**Comment by scaddenp** [comment]
I have a quite a few extra EPSG codes that I would like to support. They are supported by apache sis, but how do make them available for the requests (and appear in the getCaps)?

**Comment by guygriffiths** [comment]
We're using `org.apache.sis.referencing.CRS.forCode(String)` to get the transformations, so if it's supported by that it should work.  There currently is no way of making CRSs appear in the capabilities document.  We only list a subset because listing every possibility was really bloating the document.
