### ISSUE TITLE
Version 2.5.0 throws NPE on structured data

### ISSUE THREAD

**Issue by john-jinghai-ma** [Reading-eScience-Centre/ncwms#72]
Structured data cannot be read properly by version 2.5.0 (tested with ncWMS2-standalone.jar, openjdk-11, Ubuntu 18.04).
The same data can be processed successfully by earlier version (tested with 2.4.0 war, Tomcat8.5, openjdk-8).
```
2020-09-24 14:57:56 ERROR DatasetConfig:227 - uk.ac.rdg.resc.edal.exceptions.EdalException loading metadata for dataset XXXXXX
uk.ac.rdg.resc.edal.exceptions.EdalException: Problem creating dataset XXXXXX at ....../*.nc
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:133)
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:75)
	at uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.createDataset(DatasetConfig.java:249)
	at uk.ac.rdg.resc.edal.catalogue.jaxb.DatasetConfig.refresh(DatasetConfig.java:209)
	at uk.ac.rdg.resc.edal.catalogue.jaxb.CatalogueConfig$1.run(CatalogueConfig.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.processVectors(CdmDatasetFactory.java:308)
	at uk.ac.rdg.resc.edal.dataset.cdm.CdmDatasetFactory.createDataset(CdmDatasetFactory.java:104)
	... 10 more
```
Although version 2.50 can now read unstructured data.

**Comment by guygriffiths** [comment]
Have you got an example data file that this is failing on?  It looks like it's a file which has multiple vector fields with the same standard names.  Support for this is new in 2.5.0, but I'm not sure why this is failing.

**Comment by john-jinghai-ma** [comment]
The root cause was a typo in the vector standard names, which leads to null return from method https://github.com/Reading-eScience-Centre/edal-java/blob/master/cdm/src/main/java/uk/ac/rdg/resc/edal/dataset/cdm/CdmDatasetFactory.java#L348
